// Generated by Countertrace from model-written properties. Trusted template; do not edit.
`default_nettype none
module ct_props_top #(parameter integer STABLE = 3) (
    input wire clk,
    input wire rst,
    input wire noisy
);
    wire clean;
    wire changed;
    `CT_DUT #(.STABLE(STABLE)) dut (.clk(clk), .rst(rst), .noisy(noisy), .clean(clean), .changed(changed));
    reg past_valid = 1'b0;
    // Environment assumption owned by this template: reset at the first edge, inputs only.
    always @(*) if (!past_valid) assume (rst);
    reg model_clean;
    reg model_changed;
    reg [1:0] model_count;
    always @(posedge clk) model_clean <= rst ? 1'b0 : ((model_count == STABLE-1 && noisy != model_clean) ? noisy : model_clean);
    always @(posedge clk) model_changed <= rst ? 1'b0 : ((model_count == STABLE-1 && noisy != model_clean) ? 1'b1 : 1'b0);
    always @(posedge clk) model_count <= rst ? 2'b0 : ((noisy == model_clean) ? 2'b0 : model_count + 1);
    always @(posedge clk) begin
        past_valid <= 1'b1;
        if (past_valid) begin
            if (1'b1) p_outputs_match: assert (clean == model_clean && changed == model_changed);
            r_outputs_match: cover (1'b1);
        end
    end
endmodule
`default_nettype wire
