// Generated by Countertrace from model-written properties. Trusted template; do not edit.
`default_nettype none
module ct_props_top #(parameter integer DEPTH = 4, parameter integer WIDTH = 8) (
    input wire clk,
    input wire rst,
    input wire wr_en,
    input wire rd_en,
    input wire [WIDTH-1:0] din
);
    wire [WIDTH-1:0] dout;
    wire full;
    wire empty;
    `CT_DUT #(.DEPTH(DEPTH), .WIDTH(WIDTH)) dut (.clk(clk), .rst(rst), .wr_en(wr_en), .rd_en(rd_en), .din(din), .dout(dout), .full(full), .empty(empty));
    reg past_valid = 1'b0;
    // Environment assumption owned by this template: reset at the first edge, inputs only.
    always @(*) if (!past_valid) assume (rst);
    reg [7:0] data_mem [0:3];
    reg [2:0] count;
    reg [1:0] head;
    reg [1:0] tail;
    reg has_read;
    reg [7:0] dout_shadow;
    wire is_full;
    wire is_empty;
    wire do_write;
    wire do_read;
    wire [1:0] next_head;
    wire [1:0] next_tail;
    wire [7:0] read_data;
    assign is_full = count == DEPTH;
    assign is_empty = count == 0;
    assign do_write = wr_en & ~is_full & ~rst;
    assign do_read = rd_en & ~is_empty & ~rst;
    assign next_head = (head + 1) % DEPTH;
    assign next_tail = (tail + 1) % DEPTH;
    assign read_data = data_mem[head];
    always @(posedge clk) count <= rst ? 0 : (do_write & do_read ? count : (do_write ? count + 1 : (do_read ? count - 1 : count)));
    always @(posedge clk) head <= rst ? 0 : (do_read ? next_head : head);
    always @(posedge clk) tail <= rst ? 0 : (do_write ? next_tail : tail);
    always @(posedge clk) has_read <= rst ? 0 : (do_read ? 1 : has_read);
    always @(posedge clk) dout_shadow <= rst ? 0 : (do_read ? read_data : dout_shadow);
    always @(posedge clk) if (do_write) data_mem[tail] <= din;
    always @(posedge clk) begin
        past_valid <= 1'b1;
        if (past_valid) begin
            if (1) p_empty_flag: assert (empty == is_empty);
            r_empty_flag: cover (1);
            if (1) p_full_flag: assert (full == is_full);
            r_full_flag: cover (1);
            if (has_read) p_dout_after_read: assert (dout == dout_shadow);
            r_dout_after_read: cover (has_read);
        end
    end
endmodule
`default_nettype wire
