"""Validated interface mappings for designs whose names differ from the canonical ports.

The PRD permits a validated port-name mapping and forbids arbitrary adapter
code. A mapping is declarative JSON: each canonical port maps to exactly one
DUT port, reset may be declared active-low, extra DUT outputs may be left
unconnected, and the two contract parameters map to DUT parameter names. The
trusted host turns a valid mapping into a fixed wrapper module; the DUT
source is never edited. Extra DUT outputs are not checked by the contract.
"""

from __future__ import annotations

import json
import re

from countertrace.contract import sha256_json

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,63}$")
WRAPPER = "ct_map_dut"
CANONICAL = {
    "clk": "input", "rst": "input", "wr_en": "input", "rd_en": "input",
    "din": "input", "dout": "output", "full": "output", "empty": "output",
}


class MappingError(ValueError):
    pass


def validate(mapping: dict) -> dict:
    """Return a normalized mapping or raise MappingError."""
    if not isinstance(mapping, dict):
        raise MappingError("mapping must be an object")
    allowed = {"module", "parameters", "ports", "reset_active_low", "unused_outputs"}
    if set(mapping) - allowed:
        raise MappingError(f"unknown mapping fields: {sorted(set(mapping) - allowed)}")
    module = mapping.get("module")
    if not isinstance(module, str) or not IDENT.match(module) or module == WRAPPER:
        raise MappingError("module must be a plain identifier")
    params = mapping.get("parameters") or {}
    if set(params) != {"DEPTH", "WIDTH"} or not all(isinstance(v, str) and IDENT.match(v) for v in params.values()):
        raise MappingError("parameters must map exactly DEPTH and WIDTH to identifiers")
    ports = mapping.get("ports") or {}
    if set(ports) != set(CANONICAL):
        raise MappingError(f"ports must map exactly {sorted(CANONICAL)}")
    names = list(ports.values())
    if not all(isinstance(n, str) and IDENT.match(n) for n in names) or len(set(names)) != len(names):
        raise MappingError("each canonical port must map to a distinct identifier")
    unused = mapping.get("unused_outputs") or []
    if not isinstance(unused, list) or not all(isinstance(n, str) and IDENT.match(n) for n in unused):
        raise MappingError("unused_outputs must be identifiers")
    if set(unused) & set(names):
        raise MappingError("an unused output cannot also be mapped")
    low = mapping.get("reset_active_low", False)
    if not isinstance(low, bool):
        raise MappingError("reset_active_low must be true or false")
    return {"module": module, "parameters": dict(params), "ports": dict(ports),
            "reset_active_low": low, "unused_outputs": sorted(unused)}


def digest(mapping: dict | None) -> str | None:
    return None if mapping is None else sha256_json(validate(mapping))


def expected_ports(mapping: dict) -> dict[str, tuple[str, str | None]]:
    """DUT port name -> (direction, expected range or None for one bit or unchecked)."""
    width = mapping["parameters"]["WIDTH"]
    expected = {}
    for canonical, direction in CANONICAL.items():
        rng = f"[{width}-1:0]" if canonical in ("din", "dout") else None
        expected[mapping["ports"][canonical]] = (direction, rng)
    for name in mapping["unused_outputs"]:
        expected[name] = ("output", "*")
    return expected


def wrapper(mapping: dict) -> str:
    """Generate the trusted wrapper. Every identifier was validated above."""
    m = validate(mapping)
    p = m["ports"]
    rst = f"!rst" if m["reset_active_low"] else "rst"
    connections = [
        f".{p['clk']}(clk)", f".{p['rst']}({rst})", f".{p['wr_en']}(wr_en)", f".{p['rd_en']}(rd_en)",
        f".{p['din']}(din)", f".{p['dout']}(dout)", f".{p['full']}(full)", f".{p['empty']}(empty)",
    ] + [f".{name}()" for name in m["unused_outputs"]]
    return (
        "\n// Generated by Countertrace from validated interface mapping "
        f"{digest(m)}. Trusted wrapper; not DUT code.\n"
        f"module {WRAPPER} #(parameter integer DEPTH = 4, parameter integer WIDTH = 8) (\n"
        "    input wire clk, input wire rst, input wire wr_en, input wire rd_en,\n"
        "    input wire [WIDTH-1:0] din, output wire [WIDTH-1:0] dout, output wire full, output wire empty);\n"
        f"    {m['module']} #(.{m['parameters']['DEPTH']}(DEPTH), .{m['parameters']['WIDTH']}(WIDTH)) u_dut (\n        "
        + ", ".join(connections) + ");\nendmodule\n"
    )


def load(path) -> dict:
    from pathlib import Path

    return validate(json.loads(Path(path).read_text()))
