// Generated by Countertrace from model-written properties. Trusted template; do not edit.
`default_nettype none
module ct_props_top #(parameter integer DEPTH = 4, parameter integer WIDTH = 8) (
    input wire clk,
    input wire rst,
    input wire wr_en,
    input wire rd_en,
    input wire [WIDTH-1:0] din
);
    wire [WIDTH-1:0] dout;
    wire full;
    wire empty;
    `CT_DUT #(.DEPTH(DEPTH), .WIDTH(WIDTH)) dut (.clk(clk), .rst(rst), .wr_en(wr_en), .rd_en(rd_en), .din(din), .dout(dout), .full(full), .empty(empty));
    reg past_valid = 1'b0;
    // Environment assumption owned by this template: reset at the first edge, inputs only.
    always @(*) if (!past_valid) assume (rst);
    reg [7:0] mem [0:3];
    reg [1:0] head;
    reg [1:0] tail;
    reg [2:0] count;
    wire is_empty;
    wire is_full;
    wire read_accepted;
    wire write_accepted;
    reg ct_past0;
    reg [63:0] ct_past1;
    assign is_empty = count == 0;
    assign is_full = count == DEPTH;
    assign read_accepted = rd_en && !is_empty;
    assign write_accepted = wr_en && !is_full;
    always @(posedge clk) head <= rst ? 0 : (read_accepted ? ((head + 1) % DEPTH) : head);
    always @(posedge clk) tail <= rst ? 0 : (write_accepted ? ((tail + 1) % DEPTH) : tail);
    always @(posedge clk) count <= rst ? 0 : (count + (write_accepted ? 1 : 0) - (read_accepted ? 1 : 0));
    always @(posedge clk) if (write_accepted) mem[tail] <= din;
    always @(posedge clk) begin
        past_valid <= 1'b1;
        if (past_valid) begin
            if (1) p_full_matches: assert (full == is_full);
            r_full_matches: cover (1);
            if (1) p_empty_matches: assert (empty == is_empty);
            r_empty_matches: cover (1);
            if (ct_past0) p_dout_after_read: assert (dout == ct_past1);
            r_dout_after_read: cover (ct_past0);
        end
    end
    always @(posedge clk) ct_past0 <= (read_accepted);
    always @(posedge clk) ct_past1 <= (mem[head]);
endmodule
`default_nettype wire
